### ISSUE TITLE
bug(bin): error received 'stencil: command not found'

### ISSUE THREAD

**Issue by RiteshSRajput** [ionic-team/stencil-component-starter#116] opened 2023-01-24 09:20 UTC
sh: stencil: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! stencil-starter-project-name@0.0.1 start: `stencil build --dev --watch --serve`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the stencil-starter-project-name@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I tried by installing stencil using --global but not working

**Comment by rwaskiewicz** [comment] 2023-01-24 12:56
Hey @RiteshSRajput 👋 

Can you please provide us with steps to reproduce this error? Specifically, can you provide us with the exact terminal commands you used in order to get to this error?

I'm unable to reproduce this myself with the following commands:
```
 npm init stencil component stencil-tester
 cd stencil-tester
 npm i
 npm start
```

Let me know if you're doing something differently. Thanks!

**Comment by RiteshSRajput** [comment] 2023-01-30 06:01
sh: stencil: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! stencil-starter-project-name@0.0.1 start: `stencil build --dev --watch --serve`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the stencil-starter-project-name@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/e065698/.npm/_logs/2023-01-30T06_00_54_025Z-debug.log

**Comment by RiteshSRajput** [comment] 2023-01-30 06:01
sh: stencil: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! stencil-starter-project-name@0.0.1 start: `stencil build --dev --watch --serve`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the stencil-starter-project-name@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/e065698/.npm/_logs/2023-01-30T06_00_54_025Z-debug.log

**Comment by rwaskiewicz** [comment] 2023-01-30 13:00
Hey @RiteshSRajput,

It's not immediately clear what commands you ran based on what you provided. I can see that 'sh: stencil: command not found' was the error, but I'm not sure what command you ran that gave you that error. Can you please provide the team and I with:
1.  the exact terminal commands you used in order to get to this error
2. the contents of the error log, `/Users/e065698/.npm/_logs/2023-01-30T06_00_54_025Z-debug.log`?

That should be able to help us determine what the issue may be, and if there are any improvements we can make to the stencil project initialization workflow. 

Thanks!

**Comment by rwaskiewicz** [comment] 2023-03-13 14:17
Closing this issue, as we do not have a reproduction case. If the problem persists, please open a new issue with a reproduction case. Thanks!

**Closed by rwaskiewicz** 2023-03-13 14:17 UTC
Labels: ionitron: needs reproduction
